---
Name: membermgmtconfig
---
SilverStripe\Security\Member:
  extensions:
    - Dynamic\Members\ORM\DynamicMemberDataExtension
  max_profile_image_size: 512000
  max_profile_image_size: .512
Dynamic\Members\Controller\Registration_Controller:
  RegistrationTitle: 'Register for an account'