---
Name: membermgmtconfig
---
Member:
  extensions:
    - DynamicMemberDataExtension
  max_profile_image_size: 512000
  max_profile_image_size: .512
Registration_Controller:
  RegistrationTitle: 'Register for an account'