---
Name: membermgmtroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'RegistrationController//$Action/$ID/$Name': 'Dynamic\Profiles\Controller\RegistrationController'
    'register//$Action/$ID/$Name': 'Dynamic\Profiles\Controller\RegistrationController'
    'ProfileController//$Action/$ID/$Name': 'Dynamic\Profiles\Controller\ProfileController'
    'profile//$Action/$ID/$Name': 'Dynamic\Profiles\Controller\ProfileController'
